services:
  db:
    image: postgres:16-alpine
    container_name: messenger_db_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-messenger_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-miss_db}
    ports:
      - "5432:5432" # Пробрасываем порт для подключения с вашего ПК
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: messenger_redis_dev
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata_dev:
